package com.kastack.vidyanet.models.settings

import kotlin.time.Instant
import kotlinx.serialization.Serializable

@Serializable
data class BackupSnapshotDto(
    val id: String,
    val name: String,
    val timestamp: Instant,
    val size: String,
    val createdBy: String,
    val storageLocation: String,
    val isAutoGenerated: Boolean
)

@Serializable
data class BackupConfigDto(
    val dailyEnabled: Boolean = true,
    val weeklyEnabled: Boolean = false,
    val dailyScheduledTime: String = "02:00 AM",
    val storageProvider: BackupStorageProvider = BackupStorageProvider.AWS_S3
)

@Serializable
enum class BackupStorageProvider {
    AWS_S3, GOOGLE_DRIVE, DROPBOX
}
